list: $/zotovda/content/models/reviews/columns.yaml
modelClass: Zotovda\Content\Models\Reviews
title: Reviews
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'zotovda/content/reviews/update/:id'
