name: Team
form: $/zotovda/content/models/team/fields.yaml
modelClass: Zotovda\Content\Models\Team
defaultRedirect: zotovda/content/team
create:
    redirect: 'zotovda/content/team/update/:id'
    redirectClose: zotovda/content/team
update:
    redirect: zotovda/content/team
    redirectClose: zotovda/content/team
