list: $/zotovda/content/models/team/columns.yaml
modelClass: Zotovda\Content\Models\Team
title: Team
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'zotovda/content/team/update/:id'
