list: $/zotovda/content/models/footerlogos/columns.yaml
modelClass: Zotovda\Content\Models\FooterLogos
title: FooterLogos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'zotovda/content/footerlogos/update/:id'
