title: Events
modelClass: Zotovda\Events\Models\Events
list: $/zotovda/events/models/events/columns.yaml
recordUrl: 'zotovda/events/events/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
